- name: Initialize cluster (main node)
  hosts: mains
  roles:
    - cluster
  become: yes
  gather_facts: no
  tasks:
    - name: Initialize the cluster (Flannel)
      shell: kubeadm init --apiserver-advertise-address {{ ansible_host }} --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      tags:
        - init

    - name: Create .kube directory
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        mode: 0755

    - name: Setup kubeconfig for {{ ansible_user }}
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: '{{ ansible_user }}'

    - name: Install Pod network (Flannel)
      become: no
      become_user: '{{ ansible_user }}'
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt

    - name: Get join command
      shell: 'kubeadm token create --print-join-command 2>/dev/null'
      register: join_command_output
      changed_when: false

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_output.stdout }}"

- name: Worker joins K8s cluster (worker node)
  hosts: workers
  roles:
    - cluster
  become: yes
  gather_facts: yes
  tasks:
    - name: Join cluster
      shell: "{{ hostvars[hostvars[inventory_hostname].pair].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
